### ISSUE TITLE
Error when reading the coverage report and it is very large

### ISSUE THREAD

**Issue by ctorresMural** [ScaCap/code-coverage-assistant#49]
I am trying to integrate this action into my project but the generated coverage report is very large.  Do you have any idea how I can solve this problem?
I understand that it is part of the full report where it fails to show the coverage for each file, this can be skipped and only show the summary report with the total percentage.

```
usr/bin/docker exec  7db20cfb5c84166980f0d886cbd3f46610a6b296d73ed9b3b21d59fb94c23998 sh -c "cat /etc/*release | grep ^ID"
Ha [HttpError]: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
    at /__w/_actions/ScaCap/code-coverage-assistant/v1.1/dist/main.js:7:315302
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /__w/_actions/ScaCap/code-coverage-assistant/v1.1/dist/main.js:7:391071 {
  status: 422,
```

**Comment by eeshdarthvader** [comment]
Hi @ctorresMural , i will have a look at it soon. Feel free to raise a PR if it's urgent.
